nname: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day (UTC)
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: anuragpras # Replace with your GitHub username
          outputs: dist/snake.svg

      # Step 3: Push the generated snake to the output branch
      - name: Push Snake to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
